// sidebars.js

const sidebars = {
  // Auto-generated docs sidebar
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  
  // Tutorials sidebar
  tutorials: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;